### ISSUE TITLE
Not optimal parallelization?

### ISSUE THREAD

**Issue by henry2004y** [cbellei/Diffusion.jl#2]
Hi,

When I looked at the source code in detail, I found one key issue: your u and u0 has the size of the whole grid domain, but you only update the subdomain that actually "owns" the data. This means that for each processor, there are memories that's never going to be used. For a simple demonstration of parallel programming in Julia this might be fine, but obviously it is not an efficient parallel solver.

Besides, I do have a question about using MPI with Julia. We know that JIT takes time to compile the code the first time. The way we are using MPI with Julia right now seems to always make the repetitive compilation unavoidable. Is that true? If so, then maybe other built-in parallelization methods are more favorable than using this MPI wrapper.

Best,

**Comment by cbellei** [comment]
Hi henry2004y,

Yes I agree with you that the code can be optimized in terms of memory usage. As you say, this is really a simple demonstration so I did not bother going too much into these details.

Regarding the time for compiling the code, it is indeed rather slow compared to a Fortran / C implementation. I agree that this is sub-optimal, on the other hand there are all the other advantages of Julia that may compensate for this.

On a related note, while on my personal laptop the Julia implementation was even faster than the Fortran / C one I have done the same benchmark on a different machine and in that case Fortran was by far the fastest (by - if I remember right - up to a factor 2x with respect to Julia). I think it is reasonable to expect Julia to arrive 3rd in these kind of benchmarks (although not by a lot), this is another consideration to make.

Best,
Claudio
